#Please specify either the version or the full url for the following components
node.version=10.6.3
ogmios.version=6.14.0
kupo.version=2.11.0

yaci.store.tag=rel-native-2.0.0
yaci.store.version=2.0.0
yaci.store.jar.version=2.0.0

yano.tag=v0.1.0-pre1
yano.version=0.1.0-pre1

#node.url=
#ogmios.url=
#kupo.url=
#yaci.store.url=
#yaci.store.jar.url=
#yano.url=
