name: Manual Yaci Devkit Docker Zip upload

on:
  workflow_dispatch:

jobs:
  upload-release-docker-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Get Tag from version file
        run: |
          TAG=$(grep "tag=" config/version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      - name: Run build
        run: earthly +zip --tag ${{ env.TAG }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/yaci-devkit-${{env.TAG}}.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
