name: Publish Viewer to NPM registry

on:
  push:
    tags:
      - 'rel-viewer-*'

jobs:
  npm-publish:
    runs-on: "ubuntu-20.04"
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Get Tag from version file
        run: |
          TAG=$(grep "tag=" config/version | cut -d'=' -f2)
          echo "TAG=${TAG}" >> $GITHUB_ENV    

      - name: Set npm package version
        working-directory: applications/viewer
        run: npm version ${{ env.TAG }} --no-git-tag-version

      - name: Configure npm for scoped package
        run: |
          echo "@my-org:registry=https://registry.npmjs.org/" >> ~/.npmrc 

      - name: NPM Build
        working-directory: applications/viewer
        run: npm run build

      - name: Publish to npm
        working-directory: applications/viewer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
